name: Develop

on:
  push:
    branches: ["develop"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Secret in Pipeline
        run: echo "My secret is ${{ secrets.MOB_NU }}"
        run: echo "Hello world"
        env:
          MY_SECRET: ${{ secrets.MOB_NU }}
